name: Publish to main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Gulp CLI
      run: npm install -g gulp-cli

    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v4.2.2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Run Gulp
      run: gulp build

    - name: Copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH2 }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "${{ secrets.REMOTE_DIR_MAIN }}themes/scoutingoost1-theme"